Добавил скелет макета, добавил файл каталога и пару изображений
htmlacademy-htmlcss/1631267-technomart-30 pull request #2
Opened 2021-01-22 22:01 UTC by Konstantin9658

Сверстал главную страницу сайта, добавил файл catalog.html, добавил пару изображений из Figma

2021-01-23 12:04 UTC, Zakamsky requested changes
Отличная работа, чувствуется хорошее понимание материала и старательное исполнение, но есть ряд небольших техничесикх моментов, думаю внести правки не составит труда. 
В остальном очень аккуратно все, ты хорошо постарался, и еще раз спасибо за комментарии.

2021-01-23 12:04 UTC, Zakamsky commented on index.html
> +  <p>Разработано-<br><a href="#">htmlacademy.ru</a></p>
Такое ощущение что эти тэги потерялись и выпали из секции "Соц.сети, обратная связь, копирайт"

2021-01-23 13:17 UTC, Konstantin9658 commented
Спасибо большое! Очень приятно за оценку.  Да труда не составит, сегодня к вечеру сделаю! По поводу последнего пункта: где соц сети и тд. Это я так разметил, наверно было уже поздно и всунул куда нибудь, чтобы было. Приведу в порядок.  «Тут казалось бы все в порядке, так тоже можно, НО наверное тут где то должна быть ссылка на страницу товара...з.ы. молодец что сразу нашел все кнопки в стайлгайде, ну и не всегда очевидно - но имеет смысл иметь одинаковую структуру для карточек товаров на главной и в каталоге, по сути это один и тот же блок, зачем его два раза верстать?» Не совсем понял про каталог? Это на будущее типо или я не понял что то? У меня просто каталога пока ещё нет 23.01.2021, 15:04, "Aleksei Elkin" <notifications@github.com>:
@Zakamsky requested changes on this pull request.

Отличная работа, чувствуется хорошее понимание материала и старательное исполнение, но есть ряд небольших техничесикх моментов, думаю внести правки не составит труда.
В остальном очень аккуратно все, ты хорошо постарался, и еще раз спасибо за комментарии.

In index.html:
> +    <section>
+      <ul>
+        <li>
+          <h2>Материалы <span>NEW</span></h2>

Тут немного сбит с толку валидатор, он нашел внутри секции заголовок и успокоился, но по сути наши заголовки категорий - не являются заголовком секции, т.ч. тут стоило бы добавить скрытый заголовок для секции.



In index.html:
> +          <div>
+            <h2>Перфораторы</h2>
+            <p>Настоящие мужские игрушки</p>
+            <button type="button" value="left"></button>
+            <button type="button" value="right"></button>
+            <a href="catalog.html">Открыть каталог</a>
+          </div>
+          <div>
+            <h2>Дрели</h2>
+            <p>Соседям на радость</p>
+            <button type="button" value="left"></button>
+            <button type="button" value="right"></button>
+            <a href="catalog.html">Открыть каталог</a>
+          </div>
+          <!--Не знаю как обозначить эти штучки, которые на слайдере в виде радиокнопок. Может это и есть кнопка?-->
+          <button type="button"></button>
+          <button type="button"></button>

Тут ты полностью прав на счет кнопок, но есть небольшой нюанс:
стрелочки влево вправо, и кнопочки внизу - это элементы именно слайдера, а не слайдов. подсмотри в структуру макета.
И небольшая подсказка - для кнопочек круглых внизу пригодится какая то обертка, при стилизации, т.к. технически их может быть и больше если добавят слайды, т.ч. было бы некорректно позиционировать каждую кнопку в отдельности.
з.ы. отдельное спасибо за комментарий, очень помогает понять твой ход мыслей и помочь где нужно. Они и для себя бывают полезны.



In index.html:
> +            <figure>
+              <!--Может я слишком заморачиваюсь в оформлении карточек популярных товаров? Или так тоже можно?-->
+              <img src="https://via.placeholder.com/184x164" width="184" height="164" alt="Перфоратор BOSCH BFG 9000">
+              <figcaption>Перфоратор BOSCH<br>BFG 9000</figcaption>
+            </figure>
+            <p><s>32500 Р.</s></p>
+            <button type="button">25500 Р.</button>
+            <button type="button">Купить</button>
+            <button type="button">В закладки</button>

Тут казалось бы все в порядке, так тоже можно, НО наверное тут где то должна быть ссылка на страницу товара...
з.ы. молодец что сразу нашел все кнопки в стайлгайде, ну и не всегда очевидно - но имеет смысл иметь одинаковую структуру для карточек товаров на главной и в каталоге, по сути это один и тот же блок, зачем его два раза верстать?



In index.html:
> +  <ul>
+    <li><a href="#">ВКонтакте</a></li>
+    <li><a href="#">Facebook</a></li>
+    <li><a href="#">Instagram</a></li>
+  </ul>
+  <p>Обратная связь:<br><a href="mailto:mail@htmlacademy.ru">mail@htmlacademy.ru</a></p>
+  <p>Разработано-<br><a href="#">htmlacademy.ru</a></p>

Такое ощущение что эти тэги потерялись и выпали из секции "Соц.сети, обратная связь, копирайт"

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-24 12:22 UTC, Konstantin9658 commented
Внес правки

2021-01-24 13:25 UTC, merged