Графика всех страниц
htmlacademy-htmlcss/1631267-technomart-30 pull request #4
Opened 2021-01-26 19:06 UTC by Konstantin9658

2021-01-26 22:58 UTC, Zakamsky requested changes
Отлично все разобрал и импортировал, есть некоторые проблемы с заглавными буквами в именах файлов, надо их заменить. Не забудь так же поменять и проверить все пути, т.к. виндоус будет продолжать показывать картинки с новым названием по старому пути т.к. она регитсронезависимая а вот на сервере все сломается. 

И еще одно замечание есть по разделению графики на контентную и оформительскую - это слайдер. есть отличный пример в статье в вашем учебнике.
Дело в том что этот слайдер должен продавать, изображение в нем очень важно, скорее всего там конкретный товар, а возможно даже специально нанятая модель и заказная фотосъемка =) т.ч. давай его перенесем в контент, пока владелец магазина не расстроился.

2021-01-26 22:58 UTC, Zakamsky commented on catalog.html
> +                            <input type="radio" name="power" id="battery-id" value="Аккумуляторные" checked>
молодец, разобрался!

2021-01-26 22:58 UTC, Zakamsky commented on catalog.html
> +                                <a><img src="img/BFG6000.png" width="144" height="128"
Пройдись пожалуйста по всему проекту и избавься от заглавных букв в именах фалов и путях, кроме служебных файлов. Это дурной тон в разработке, т.к. во первых названия с больших букв используются для определенных целей - отличать объекты от классов в программировании например. И потом это может выстрелить в ногу при работе с разным ос, например виндоус не делает различия в регистре, а Unix системы делают и мы можем сломать проект при переносе из одной ос в другую.
А начать наверное стоило с того что это базовый критерий...

2021-01-26 22:58 UTC, Zakamsky commented on catalog.html
> +    <link rel="manifest" href="manifest.webmanifest.json">
Тут есть некоторая путаница, json в данном случае это формат данных внутри, а расширение файла принято использовать .webmanifest
И хотя большинство браузеров примут и другое расширение, для явного понимания и полной поддержки я бы советовал придерживаться такого именования: manifest.webmanifest
https://developer.mozilla.org/ru/docs/Web/Manifest#deploying_a_manifest_with_the_link_tag

т.е. это строго говоря не ошибка, просто совет. ну раз уж мы будем все равно вносить правки...

2021-01-26 22:58 UTC, Zakamsky commented on catalog.html
> +            <a href="index.html"><img src="img/logo/logo.png" width="220" height="68" alt="Логотип «Техномарт»"></a>
тут разумнее было бы использовать ту же картинку что и логотипе вверху, с теми же эффектами для ссылки.

2021-01-27 06:40 UTC, Konstantin9658 commented
Графика всех страниц

2021-01-27 14:16 UTC, merged